### ISSUE TITLE
Completion to work after build with Makefile

### ISSUE THREAD

**Issue by sswastik02** [dypflying/go-qcow2lib#10]
The cobra project [name](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/Makefile#L10) and the [name](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/cmd/subcmd/cmd.go#L31) of the binary when built with `make` should be the same to ensure completion works as intended

**Comment by sswastik02** [comment]
Hi @dypflying,
If you think this issue is valid, I am happy to submit a PR.

Thanks

**Comment by dypflying** [comment]
Hi @sswastik02 

Sorry for the late replay,  the issue is valid and I think any enhancement is valid and be glad to have it:)

Thanks

**Comment by sswastik02** [comment]
Thank you, will submit a PR shortly
