### ISSUE TITLE
Create option should allow to specify format of the backing file

### ISSUE THREAD

**Issue by sswastik02** [dypflying/go-qcow2lib#9]
Backing file format comes under the `header extensions` section of the qcow image, it can be specified so that services such as `libvirt` can avoid probing for it.
It would be the equivalent of the `-F` switch in `qemu-img`. Here is [something](https://libvirt.org/kbase/backing_chains.html#importance-of-proper-backing-chain-setup) for its usage.

**Comment by sswastik02** [comment]
Hi @dypflying,
I am thrilled to work on this project, Can you please validate the issue and add certain tags to indicate if this issue is valid and can be worked on? 
If so, I would gladly like to take up this issue.
Thanks.

**Comment by dypflying** [comment]
Hi @sswastik02 , 
   Glad to hear you would work on this project as well, and of course you can make any changes on this project,  which still lacks of lots of features that QEMU library has. 
    I just labeled this issue as an "enhancement", any further information or support, please feel free to let me know,

**Comment by sswastik02** [comment]
Thank you so much for your prompt reply and action @dypflying.
Here is the high-level plan of the changes proposed:
1. Add an option in the [consts](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/consts.go#L197) file called `OPT_BACKING_FORMAT` to store the format of the backing file
2. Create a struct known as `Qcow2HeaderExtension` in the [types](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/types.go) file.
3. Something similar to [this](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/qcow2.go#L182) to write the header extension into the file

l would greatly appreciate it if you could review the above plan and suggest any changes as you see fit, and also please assign this issue to me.

**Comment by dypflying** [comment]
Hi @sswastik02 
    The solution looks good to me, but just a kindly reminder that current implementation doesn't support other format of backing file like qed, qcow, etc.
     just assigned the issue to you. 
 
Thanks 
BR

**Comment by sswastik02** [comment]
Hey, @dypflying 
Can you please elaborate on this?

> current implementation doesn't support other format of backing file

what kind of support are you talking about? Do you mean opening the file with a backing file of `qcow2` type?
Thanks for assigning the issue to me.

**Comment by dypflying** [comment]
> Can you please elaborate on this?
> 
> >
The current Golang  library only handles RAW  and QCOW2 format files, but it can not handle other format such as QED, QCOW, etc files like qemu. 

BR

**Comment by sswastik02** [comment]
Ok sure, I guess we will find out, I'll get started with the plan and keep you updated.
Thanks.

**Comment by sswastik02** [comment]
Hi @dypflying ,

Can you please confirm if the use of this [function](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/qcow2.go#L865) is to write header extension into the qcow2 file and if [this](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/types.go#L434) was meant to be used for header extension? 

Thanks.

**Comment by dypflying** [comment]
> Can you please confirm if the use of this [function](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/qcow2.go#L865) is to write header extension into the qcow2 file
This is just a function to write a "external data file name" header extension, while qemu implemented several kinds of header extension, details are from https://github.com/qemu/qemu/blob/master/docs/interop/qcow2.txt. 

> and if [this](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/types.go#L434) was meant to be used for header extension?
It is a Golang structure represents a "header extension", normally it consists of a magic number for a kind of specific header extension and the length of data, followed by the real data that needs to be stored.

**Comment by sswastik02** [comment]
Hi @dypflying,
I just wanted to know if `DataFile` is the only header extension that you have implemented, as you directly write the header extension right after the `Qcow2Header` over [here](https://github.com/dypflying/go-qcow2lib/blob/b3c08051446fe8647a8e710825ef816c3bac0385/qcow2/qcow2.go#L187)

Thanks.

**Comment by dypflying** [comment]
Hi @sswastik02 
Sorry for the late reply:(. Yes, I only implemented the "Datefile" header extension.  It's better have a general function for the header extension.

**Comment by sswastik02** [comment]
Thank you so much, I will make a PR shortly.

**Comment by sswastik02** [comment]
Hi @dypflying ,
I wanted to ask about the [mechanism](https://github.com/dypflying/go-qcow2lib/blob/2ef44865823c17257c2acd2b54c9f50dbee86bb2/qcow2/qcow2.go#L75) in which data is written to a qcow2 disk while creating it. 

Are the offsets to everything (you have implemented) written to the qcow2 disk predefined? Or Is there some other mechanism for writing data every time to the qcow2 disk?

Thank you.

**Comment by sswastik02** [comment]
@dypflying , Thank you for accepting the changes.
